export const inheritXABI = [
  { inputs: [], name: "AccessControlBadConfirmation", type: "error" },
  {
    inputs: [
      { internalType: "address", name: "account", type: "address" },
      { internalType: "bytes32", name: "neededRole", type: "bytes32" },
    ],
    name: "AccessControlUnauthorizedAccount",
    type: "error",
  },
  {
    inputs: [{ internalType: "address", name: "target", type: "address" }],
    name: "AddressEmptyCode",
    type: "error",
  },
  {
    inputs: [
      { internalType: "address", name: "implementation", type: "address" },
    ],
    name: "ERC1967InvalidImplementation",
    type: "error",
  },
  { inputs: [], name: "ERC1967NonPayable", type: "error" },
  { inputs: [], name: "EnforcedPause", type: "error" },
  { inputs: [], name: "ExpectedPause", type: "error" },
  { inputs: [], name: "FailedCall", type: "error" },
  {
    inputs: [
      { internalType: "uint256", name: "required", type: "uint256" },
      { internalType: "uint256", name: "allowance", type: "uint256" },
    ],
    name: "InsufficientAllowance",
    type: "error",
  },
  {
    inputs: [
      { internalType: "address", name: "user", type: "address" },
      { internalType: "uint256", name: "required", type: "uint256" },
      { internalType: "uint256", name: "available", type: "uint256" },
    ],
    name: "InsufficientUserBalance",
    type: "error",
  },
  {
    inputs: [{ internalType: "uint8", name: "assetType", type: "uint8" }],
    name: "InvalidAssetType",
    type: "error",
  },
  { inputs: [], name: "InvalidBeneficiaries", type: "error" },
  { inputs: [], name: "InvalidInitialization", type: "error" },
  { inputs: [], name: "InvalidInput", type: "error" },
  {
    inputs: [{ internalType: "uint8", name: "percentage", type: "uint8" }],
    name: "InvalidPercentage",
    type: "error",
  },
  {
    inputs: [{ internalType: "uint8", name: "sum", type: "uint8" }],
    name: "InvalidPercentageSum",
    type: "error",
  },
  {
    inputs: [{ internalType: "uint256", name: "max", type: "uint256" }],
    name: "MaxBeneficiariesReached",
    type: "error",
  },
  { inputs: [], name: "NotInitializing", type: "error" },
  { inputs: [], name: "TransferFailed", type: "error" },
  { inputs: [], name: "UUPSUnauthorizedCallContext", type: "error" },
  {
    inputs: [{ internalType: "bytes32", name: "slot", type: "bytes32" }],
    name: "UUPSUnsupportedProxiableUUID",
    type: "error",
  },
  { inputs: [], name: "ZeroAddress", type: "error" },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "planId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "beneficiary",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "feeAmount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "feePercentage",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "grossAmount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "netAmount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "address",
        name: "feeRecipient",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint64",
        name: "collectedAt",
        type: "uint64",
      },
    ],
    name: "FeeCollected",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint64",
        name: "version",
        type: "uint64",
      },
    ],
    name: "Initialized",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "Paused",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "planId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        indexed: false,
        internalType: "string",
        name: "planName",
        type: "string",
      },
      {
        indexed: false,
        internalType: "string",
        name: "planDescription",
        type: "string",
      },
      {
        indexed: false,
        internalType: "string",
        name: "beneficiaryName",
        type: "string",
      },
      {
        indexed: false,
        internalType: "string",
        name: "beneficiaryRelationship",
        type: "string",
      },
      {
        indexed: false,
        internalType: "string",
        name: "beneficiaryEmail",
        type: "string",
      },
      {
        indexed: false,
        internalType: "uint8",
        name: "assetType",
        type: "uint8",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "assetAmount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint8",
        name: "distributionMethod",
        type: "uint8",
      },
      {
        indexed: false,
        internalType: "uint64",
        name: "createdAt",
        type: "uint64",
      },
    ],
    name: "PlanCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "bytes32", name: "role", type: "bytes32" },
      {
        indexed: true,
        internalType: "bytes32",
        name: "previousAdminRole",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "newAdminRole",
        type: "bytes32",
      },
    ],
    name: "RoleAdminChanged",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "bytes32", name: "role", type: "bytes32" },
      {
        indexed: true,
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "sender",
        type: "address",
      },
    ],
    name: "RoleGranted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "bytes32", name: "role", type: "bytes32" },
      {
        indexed: true,
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "sender",
        type: "address",
      },
    ],
    name: "RoleRevoked",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "Unpaused",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "implementation",
        type: "address",
      },
    ],
    name: "Upgraded",
    type: "event",
  },
  {
    inputs: [],
    name: "ADMIN_ROLE",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "DEFAULT_ADMIN_ROLE",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "GUARDIAN_ROLE",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "OPERATOR_ROLE",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "PLAN_CREATION_FEE",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "UPGRADE_INTERFACE_VERSION",
    outputs: [{ internalType: "string", name: "", type: "string" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "", type: "uint256" },
      { internalType: "address", name: "", type: "address" },
    ],
    name: "beneficiaryByAddress",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "string", name: "planName", type: "string" },
      { internalType: "string", name: "planDescription", type: "string" },
      {
        components: [
          { internalType: "string", name: "name", type: "string" },
          { internalType: "string", name: "email", type: "string" },
          { internalType: "string", name: "relationship", type: "string" },
        ],
        internalType: "struct BeneficiaryInput[]",
        name: "beneficiaries",
        type: "tuple[]",
      },
      { internalType: "uint8", name: "assetType", type: "uint8" },
      { internalType: "uint256", name: "assetAmount", type: "uint256" },
      { internalType: "uint8", name: "distributionMethod", type: "uint8" },
      { internalType: "uint64", name: "lumpSumDate", type: "uint64" },
      { internalType: "uint8", name: "quarterlyPercentage", type: "uint8" },
      { internalType: "uint8", name: "yearlyPercentage", type: "uint8" },
      { internalType: "uint8", name: "monthlyPercentage", type: "uint8" },
      { internalType: "string", name: "additionalNote", type: "string" },
      { internalType: "string", name: "claimCode", type: "string" },
    ],
    name: "createInheritancePlan",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "dexRouter",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "distributionConfigs",
    outputs: [
      {
        internalType: "enum DistributionMethod",
        name: "distributionMethod",
        type: "uint8",
      },
      { internalType: "uint64", name: "lumpSumDate", type: "uint64" },
      { internalType: "uint8", name: "quarterlyPercentage", type: "uint8" },
      { internalType: "uint8", name: "yearlyPercentage", type: "uint8" },
      { internalType: "uint8", name: "monthlyPercentage", type: "uint8" },
      { internalType: "string", name: "additionalNote", type: "string" },
      { internalType: "uint64", name: "startDate", type: "uint64" },
      { internalType: "uint64", name: "endDate", type: "uint64" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "distributionPlans",
    outputs: [
      { internalType: "uint256", name: "planId", type: "uint256" },
      { internalType: "address", name: "owner", type: "address" },
      { internalType: "uint256", name: "totalAmount", type: "uint256" },
      {
        internalType: "enum DistributionMethod",
        name: "distributionMethod",
        type: "uint8",
      },
      { internalType: "uint256", name: "periodAmount", type: "uint256" },
      { internalType: "uint64", name: "startDate", type: "uint64" },
      { internalType: "uint64", name: "endDate", type: "uint64" },
      { internalType: "uint8", name: "totalPeriods", type: "uint8" },
      { internalType: "uint8", name: "completedPeriods", type: "uint8" },
      { internalType: "uint64", name: "nextDisbursementDate", type: "uint64" },
      { internalType: "bool", name: "isActive", type: "bool" },
      { internalType: "uint8", name: "beneficiariesCount", type: "uint8" },
      {
        internalType: "enum DisbursementStatus",
        name: "disbursementStatus",
        type: "uint8",
      },
      { internalType: "uint64", name: "createdAt", type: "uint64" },
      { internalType: "uint64", name: "lastActivity", type: "uint64" },
      { internalType: "uint64", name: "pausedAt", type: "uint64" },
      { internalType: "uint64", name: "resumedAt", type: "uint64" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "emergencyWithdrawAddress",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "escrowAccounts",
    outputs: [
      { internalType: "uint256", name: "id", type: "uint256" },
      { internalType: "uint256", name: "planId", type: "uint256" },
      { internalType: "enum AssetType", name: "assetType", type: "uint8" },
      { internalType: "uint256", name: "amount", type: "uint256" },
      { internalType: "uint256", name: "nftTokenId", type: "uint256" },
      { internalType: "address", name: "nftContract", type: "address" },
      { internalType: "bool", name: "isLocked", type: "bool" },
      { internalType: "uint64", name: "lockedAt", type: "uint64" },
      { internalType: "address", name: "beneficiary", type: "address" },
      { internalType: "uint8", name: "releaseConditionsCount", type: "uint8" },
      { internalType: "uint256", name: "fees", type: "uint256" },
      { internalType: "uint256", name: "taxLiability", type: "uint256" },
      { internalType: "uint64", name: "lastValuation", type: "uint64" },
      { internalType: "uint256", name: "valuationPrice", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "escrowCount",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "feeConfig",
    outputs: [
      { internalType: "uint256", name: "feePercentage", type: "uint256" },
      { internalType: "address", name: "feeRecipient", type: "address" },
      { internalType: "bool", name: "isActive", type: "bool" },
      { internalType: "uint256", name: "minFee", type: "uint256" },
      { internalType: "uint256", name: "maxFee", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "role", type: "bytes32" }],
    name: "getRoleAdmin",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "globalPlanIdToUser",
    outputs: [
      { internalType: "address", name: "user", type: "address" },
      { internalType: "uint256", name: "userPlanId", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "role", type: "bytes32" },
      { internalType: "address", name: "account", type: "address" },
    ],
    name: "grantRole",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "role", type: "bytes32" },
      { internalType: "address", name: "account", type: "address" },
    ],
    name: "hasRole",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "inheritancePlans",
    outputs: [
      { internalType: "uint256", name: "id", type: "uint256" },
      { internalType: "address", name: "owner", type: "address" },
      { internalType: "uint8", name: "beneficiaryCount", type: "uint8" },
      { internalType: "enum AssetType", name: "assetType", type: "uint8" },
      { internalType: "uint256", name: "assetAmount", type: "uint256" },
      { internalType: "uint256", name: "nftTokenId", type: "uint256" },
      { internalType: "address", name: "nftContract", type: "address" },
      { internalType: "uint64", name: "timeframe", type: "uint64" },
      { internalType: "uint64", name: "createdAt", type: "uint64" },
      { internalType: "uint64", name: "becomesActiveAt", type: "uint64" },
      { internalType: "address", name: "guardian", type: "address" },
      { internalType: "string", name: "encryptedDetails", type: "string" },
      { internalType: "enum PlanStatus", name: "status", type: "uint8" },
      { internalType: "bool", name: "isClaimed", type: "bool" },
      { internalType: "bytes32", name: "claimCodeHash", type: "bytes32" },
      { internalType: "uint64", name: "inactivityThreshold", type: "uint64" },
      { internalType: "uint64", name: "lastActivity", type: "uint64" },
      { internalType: "uint256", name: "swapRequestId", type: "uint256" },
      { internalType: "uint256", name: "escrowId", type: "uint256" },
      { internalType: "uint8", name: "securityLevel", type: "uint8" },
      { internalType: "bool", name: "autoExecute", type: "bool" },
      { internalType: "uint8", name: "emergencyContactsCount", type: "uint8" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_admin", type: "address" },
      { internalType: "address", name: "_dexRouter", type: "address" },
      {
        internalType: "address",
        name: "_emergencyWithdrawAddress",
        type: "address",
      },
      { internalType: "address", name: "_primaryToken", type: "address" },
      { internalType: "address", name: "_usdtToken", type: "address" },
      { internalType: "address", name: "_usdcToken", type: "address" },
    ],
    name: "initialize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "pause",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "paused",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "", type: "uint256" },
      { internalType: "uint256", name: "", type: "uint256" },
    ],
    name: "planBeneficiaries",
    outputs: [
      { internalType: "address", name: "beneficiaryAddress", type: "address" },
      { internalType: "string", name: "name", type: "string" },
      { internalType: "string", name: "email", type: "string" },
      { internalType: "string", name: "relationship", type: "string" },
      { internalType: "bytes32", name: "claimCodeHash", type: "bytes32" },
      { internalType: "bool", name: "hasClaimed", type: "bool" },
      { internalType: "uint256", name: "claimedAmount", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "planBeneficiaryCount",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "planCount",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "planDescriptions",
    outputs: [{ internalType: "string", name: "", type: "string" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "planEscrow",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "planFeesCollected",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "planNames",
    outputs: [{ internalType: "string", name: "", type: "string" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "primaryToken",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "proxiableUUID",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "role", type: "bytes32" },
      { internalType: "address", name: "callerConfirmation", type: "address" },
    ],
    name: "renounceRole",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "role", type: "bytes32" },
      { internalType: "address", name: "account", type: "address" },
    ],
    name: "revokeRole",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "securitySettings",
    outputs: [
      { internalType: "uint8", name: "maxBeneficiaries", type: "uint8" },
      { internalType: "uint64", name: "minTimeframe", type: "uint64" },
      { internalType: "uint64", name: "maxTimeframe", type: "uint64" },
      { internalType: "bool", name: "requireGuardian", type: "bool" },
      { internalType: "bool", name: "allowEarlyExecution", type: "bool" },
      { internalType: "uint256", name: "maxAssetAmount", type: "uint256" },
      { internalType: "bool", name: "requireMultiSig", type: "bool" },
      { internalType: "uint8", name: "multiSigThreshold", type: "uint8" },
      { internalType: "uint64", name: "emergencyTimeout", type: "uint64" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes4", name: "interfaceId", type: "bytes4" }],
    name: "supportsInterface",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "totalFeesCollected",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "unpause",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "newImplementation", type: "address" },
      { internalType: "bytes", name: "data", type: "bytes" },
    ],
    name: "upgradeToAndCall",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [],
    name: "usdcToken",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "usdtToken",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "", type: "address" }],
    name: "userPlanCount",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "", type: "address" }],
    name: "userPlanIdCounter",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "", type: "address" },
      { internalType: "uint256", name: "", type: "uint256" },
    ],
    name: "userPlanIdToGlobal",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "withdrawalRequestCount",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "withdrawalRequests",
    outputs: [
      { internalType: "uint256", name: "requestId", type: "uint256" },
      { internalType: "uint256", name: "planId", type: "uint256" },
      { internalType: "address", name: "beneficiary", type: "address" },
      { internalType: "enum AssetType", name: "assetType", type: "uint8" },
      {
        internalType: "enum WithdrawalType",
        name: "withdrawalType",
        type: "uint8",
      },
      { internalType: "uint256", name: "amount", type: "uint256" },
      { internalType: "uint256", name: "nftTokenId", type: "uint256" },
      { internalType: "address", name: "nftContract", type: "address" },
      { internalType: "enum WithdrawalStatus", name: "status", type: "uint8" },
      { internalType: "uint64", name: "requestedAt", type: "uint64" },
      { internalType: "uint64", name: "processedAt", type: "uint64" },
      { internalType: "address", name: "processedBy", type: "address" },
      { internalType: "uint256", name: "feesDeducted", type: "uint256" },
      { internalType: "uint256", name: "netAmount", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
];
