/**
 * InheritX Smart Contract ABI
 * Updated for new contract with hashed beneficiary data
 */

export const inheritXABI = [
  { inputs: [], stateMutability: "nonpayable", type: "constructor" },
  { inputs: [], name: "AccessControlBadConfirmation", type: "error" },
  {
    inputs: [
      { internalType: "address", name: "account", type: "address" },
      { internalType: "bytes32", name: "neededRole", type: "bytes32" },
    ],
    name: "AccessControlUnauthorizedAccount",
    type: "error",
  },
  {
    inputs: [{ internalType: "address", name: "target", type: "address" }],
    name: "AddressEmptyCode",
    type: "error",
  },
  { inputs: [], name: "AlreadyClaimed", type: "error" },
  {
    inputs: [
      { internalType: "address", name: "implementation", type: "address" },
    ],
    name: "ERC1967InvalidImplementation",
    type: "error",
  },
  { inputs: [], name: "ERC1967NonPayable", type: "error" },
  { inputs: [], name: "EnforcedPause", type: "error" },
  { inputs: [], name: "ExpectedPause", type: "error" },
  { inputs: [], name: "FailedCall", type: "error" },
  {
    inputs: [
      { internalType: "uint256", name: "required", type: "uint256" },
      { internalType: "uint256", name: "allowance", type: "uint256" },
    ],
    name: "InsufficientAllowance",
    type: "error",
  },
  {
    inputs: [
      { internalType: "address", name: "user", type: "address" },
      { internalType: "uint256", name: "required", type: "uint256" },
      { internalType: "uint256", name: "available", type: "uint256" },
    ],
    name: "InsufficientUserBalance",
    type: "error",
  },
  {
    inputs: [{ internalType: "uint8", name: "assetType", type: "uint8" }],
    name: "InvalidAssetType",
    type: "error",
  },
  { inputs: [], name: "InvalidBeneficiaries", type: "error" },
  { inputs: [], name: "InvalidBeneficiaryData", type: "error" },
  { inputs: [], name: "InvalidClaimCode", type: "error" },
  { inputs: [], name: "InvalidInitialization", type: "error" },
  { inputs: [], name: "InvalidInput", type: "error" },
  {
    inputs: [{ internalType: "uint256", name: "percentage", type: "uint256" }],
    name: "InvalidPercentage",
    type: "error",
  },
  { inputs: [], name: "InvalidState", type: "error" },
  { inputs: [], name: "KYCAlreadySubmitted", type: "error" },
  { inputs: [], name: "KYCNotApproved", type: "error" },
  {
    inputs: [{ internalType: "uint256", name: "max", type: "uint256" }],
    name: "MaxBeneficiariesReached",
    type: "error",
  },
  { inputs: [], name: "NotInitializing", type: "error" },
  {
    inputs: [{ internalType: "uint256", name: "total", type: "uint256" }],
    name: "PercentageMustEqual100",
    type: "error",
  },
  { inputs: [], name: "PlanNotClaimable", type: "error" },
  {
    inputs: [{ internalType: "uint256", name: "planId", type: "uint256" }],
    name: "PlanNotFound",
    type: "error",
  },
  { inputs: [], name: "ReentrancyGuardReentrantCall", type: "error" },
  {
    inputs: [{ internalType: "address", name: "token", type: "address" }],
    name: "SafeERC20FailedOperation",
    type: "error",
  },
  { inputs: [], name: "TransferDateNotReached", type: "error" },
  { inputs: [], name: "UUPSUnauthorizedCallContext", type: "error" },
  {
    inputs: [{ internalType: "bytes32", name: "slot", type: "bytes32" }],
    name: "UUPSUnsupportedProxiableUUID",
    type: "error",
  },
  { inputs: [], name: "Unauthorized", type: "error" },
  { inputs: [], name: "ZeroAddress", type: "error" },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "planId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "feeAmount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "netAmount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "address",
        name: "feeRecipient",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint64",
        name: "collectedAt",
        type: "uint64",
      },
    ],
    name: "FeeCollected",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "planId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "claimer",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "beneficiaryIndex",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint64",
        name: "claimedAt",
        type: "uint64",
      },
    ],
    name: "InheritanceClaimed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint64",
        name: "version",
        type: "uint64",
      },
    ],
    name: "Initialized",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "user", type: "address" },
      {
        indexed: false,
        internalType: "enum KYCStatus",
        name: "oldStatus",
        type: "uint8",
      },
      {
        indexed: false,
        internalType: "enum KYCStatus",
        name: "newStatus",
        type: "uint8",
      },
      {
        indexed: true,
        internalType: "address",
        name: "reviewedBy",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint64",
        name: "changedAt",
        type: "uint64",
      },
    ],
    name: "KYCStatusChanged",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "Paused",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "globalPlanId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "userPlanId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint8",
        name: "assetType",
        type: "uint8",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "assetAmount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint8",
        name: "distributionMethod",
        type: "uint8",
      },
      {
        indexed: false,
        internalType: "uint64",
        name: "transferDate",
        type: "uint64",
      },
      {
        indexed: false,
        internalType: "uint8",
        name: "beneficiaryCount",
        type: "uint8",
      },
      {
        indexed: false,
        internalType: "uint64",
        name: "createdAt",
        type: "uint64",
      },
    ],
    name: "PlanCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "planId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "enum PlanStatus",
        name: "oldStatus",
        type: "uint8",
      },
      {
        indexed: false,
        internalType: "enum PlanStatus",
        name: "newStatus",
        type: "uint8",
      },
      {
        indexed: false,
        internalType: "uint64",
        name: "changedAt",
        type: "uint64",
      },
    ],
    name: "PlanStatusChanged",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "bytes32", name: "role", type: "bytes32" },
      {
        indexed: true,
        internalType: "bytes32",
        name: "previousAdminRole",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "newAdminRole",
        type: "bytes32",
      },
    ],
    name: "RoleAdminChanged",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "bytes32", name: "role", type: "bytes32" },
      {
        indexed: true,
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "sender",
        type: "address",
      },
    ],
    name: "RoleGranted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "bytes32", name: "role", type: "bytes32" },
      {
        indexed: true,
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "sender",
        type: "address",
      },
    ],
    name: "RoleRevoked",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "Unpaused",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "implementation",
        type: "address",
      },
    ],
    name: "Upgraded",
    type: "event",
  },
  {
    inputs: [],
    name: "ADMIN_ROLE",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "BPS_DENOMINATOR",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "DEFAULT_ADMIN_ROLE",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "OPERATOR_ROLE",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "PLAN_CREATION_FEE_BPS",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "UPGRADE_INTERFACE_VERSION",
    outputs: [{ internalType: "string", name: "", type: "string" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "user", type: "address" },
      { internalType: "bytes32", name: "kycDataHash", type: "bytes32" },
    ],
    name: "approveKYC",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "planId", type: "uint256" }],
    name: "cancelPlan",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "planId", type: "uint256" },
      { internalType: "string", name: "claimCode", type: "string" },
      { internalType: "string", name: "beneficiaryName", type: "string" },
      { internalType: "string", name: "beneficiaryEmail", type: "string" },
      {
        internalType: "string",
        name: "beneficiaryRelationship",
        type: "string",
      },
      { internalType: "uint256", name: "beneficiaryIndex", type: "uint256" },
    ],
    name: "claimInheritance",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "planNameHash", type: "bytes32" },
      { internalType: "bytes32", name: "planDescriptionHash", type: "bytes32" },
      {
        components: [
          { internalType: "bytes32", name: "nameHash", type: "bytes32" },
          { internalType: "bytes32", name: "emailHash", type: "bytes32" },
          {
            internalType: "bytes32",
            name: "relationshipHash",
            type: "bytes32",
          },
          {
            internalType: "uint256",
            name: "allocatedPercentage",
            type: "uint256",
          },
        ],
        internalType: "struct BeneficiaryInput[]",
        name: "beneficiaries",
        type: "tuple[]",
      },
      { internalType: "uint8", name: "assetType", type: "uint8" },
      { internalType: "uint256", name: "assetAmount", type: "uint256" },
      { internalType: "uint8", name: "distributionMethod", type: "uint8" },
      { internalType: "uint64", name: "transferDate", type: "uint64" },
      { internalType: "uint8", name: "periodicPercentage", type: "uint8" },
      { internalType: "bytes32", name: "claimCodeHash", type: "bytes32" },
    ],
    name: "createInheritancePlan",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "distributionConfigs",
    outputs: [
      {
        internalType: "enum DistributionMethod",
        name: "distributionMethod",
        type: "uint8",
      },
      { internalType: "uint64", name: "transferDate", type: "uint64" },
      { internalType: "uint8", name: "periodicPercentage", type: "uint8" },
      { internalType: "uint64", name: "startDate", type: "uint64" },
      { internalType: "uint64", name: "endDate", type: "uint64" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "distributionPlans",
    outputs: [
      { internalType: "uint256", name: "planId", type: "uint256" },
      { internalType: "address", name: "owner", type: "address" },
      { internalType: "uint256", name: "totalAmount", type: "uint256" },
      {
        internalType: "enum DistributionMethod",
        name: "distributionMethod",
        type: "uint8",
      },
      { internalType: "uint256", name: "periodAmount", type: "uint256" },
      { internalType: "uint64", name: "startDate", type: "uint64" },
      { internalType: "uint64", name: "endDate", type: "uint64" },
      { internalType: "uint8", name: "totalPeriods", type: "uint8" },
      { internalType: "uint8", name: "completedPeriods", type: "uint8" },
      { internalType: "uint64", name: "nextDisbursementDate", type: "uint64" },
      { internalType: "bool", name: "isActive", type: "bool" },
      {
        internalType: "enum DisbursementStatus",
        name: "disbursementStatus",
        type: "uint8",
      },
      { internalType: "uint64", name: "createdAt", type: "uint64" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "escrowAccounts",
    outputs: [
      { internalType: "uint256", name: "id", type: "uint256" },
      { internalType: "uint256", name: "planId", type: "uint256" },
      { internalType: "enum AssetType", name: "assetType", type: "uint8" },
      { internalType: "uint256", name: "amount", type: "uint256" },
      { internalType: "bool", name: "isLocked", type: "bool" },
      { internalType: "uint64", name: "lockedAt", type: "uint64" },
      { internalType: "uint256", name: "fees", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "escrowCount",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "feeConfig",
    outputs: [
      { internalType: "uint256", name: "feePercentage", type: "uint256" },
      { internalType: "address", name: "feeRecipient", type: "address" },
      { internalType: "bool", name: "isActive", type: "bool" },
      { internalType: "uint256", name: "minFee", type: "uint256" },
      { internalType: "uint256", name: "maxFee", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "user", type: "address" }],
    name: "getKYCStatus",
    outputs: [{ internalType: "enum KYCStatus", name: "", type: "uint8" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "planId", type: "uint256" }],
    name: "getPlanBeneficiaries",
    outputs: [
      {
        components: [
          { internalType: "bytes32", name: "nameHash", type: "bytes32" },
          { internalType: "bytes32", name: "emailHash", type: "bytes32" },
          {
            internalType: "bytes32",
            name: "relationshipHash",
            type: "bytes32",
          },
          {
            internalType: "bytes32",
            name: "beneficiaryDataHash",
            type: "bytes32",
          },
          { internalType: "address", name: "claimedBy", type: "address" },
          { internalType: "bool", name: "hasClaimed", type: "bool" },
          { internalType: "uint256", name: "claimedAmount", type: "uint256" },
          {
            internalType: "uint256",
            name: "allocatedPercentage",
            type: "uint256",
          },
        ],
        internalType: "struct Beneficiary[]",
        name: "",
        type: "tuple[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "role", type: "bytes32" }],
    name: "getRoleAdmin",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "planId", type: "uint256" }],
    name: "getTimeUntilClaimable",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "user", type: "address" }],
    name: "getUserPlans",
    outputs: [{ internalType: "uint256[]", name: "", type: "uint256[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "globalPlanIdToUser",
    outputs: [
      { internalType: "address", name: "user", type: "address" },
      { internalType: "uint256", name: "userPlanId", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "role", type: "bytes32" },
      { internalType: "address", name: "account", type: "address" },
    ],
    name: "grantRole",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "role", type: "bytes32" },
      { internalType: "address", name: "account", type: "address" },
    ],
    name: "hasRole",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "inheritancePlans",
    outputs: [
      { internalType: "uint256", name: "id", type: "uint256" },
      { internalType: "address", name: "owner", type: "address" },
      { internalType: "uint8", name: "beneficiaryCount", type: "uint8" },
      { internalType: "enum AssetType", name: "assetType", type: "uint8" },
      { internalType: "uint256", name: "assetAmount", type: "uint256" },
      { internalType: "uint64", name: "createdAt", type: "uint64" },
      { internalType: "uint64", name: "transferDate", type: "uint64" },
      { internalType: "enum PlanStatus", name: "status", type: "uint8" },
      { internalType: "bool", name: "isClaimed", type: "bool" },
      { internalType: "bytes32", name: "claimCodeHash", type: "bytes32" },
      { internalType: "uint256", name: "escrowId", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_admin", type: "address" },
      { internalType: "address", name: "_primaryToken", type: "address" },
      { internalType: "address", name: "_usdtToken", type: "address" },
      { internalType: "address", name: "_usdcToken", type: "address" },
    ],
    name: "initialize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "user", type: "address" }],
    name: "isKYCApproved",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "planId", type: "uint256" }],
    name: "isPlanClaimable",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "kycRequired",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "pause",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "planId", type: "uint256" }],
    name: "pausePlan",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "paused",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "", type: "uint256" },
      { internalType: "uint256", name: "", type: "uint256" },
    ],
    name: "planBeneficiaries",
    outputs: [
      { internalType: "bytes32", name: "nameHash", type: "bytes32" },
      { internalType: "bytes32", name: "emailHash", type: "bytes32" },
      { internalType: "bytes32", name: "relationshipHash", type: "bytes32" },
      { internalType: "bytes32", name: "beneficiaryDataHash", type: "bytes32" },
      { internalType: "address", name: "claimedBy", type: "address" },
      { internalType: "bool", name: "hasClaimed", type: "bool" },
      { internalType: "uint256", name: "claimedAmount", type: "uint256" },
      { internalType: "uint256", name: "allocatedPercentage", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "planBeneficiaryCount",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "planCount",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "planDescriptionHashes",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "planEscrow",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "planNameHashes",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "assetAmount", type: "uint256" }],
    name: "previewPlanCreationFee",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "primaryToken",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "proxiableUUID",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "user", type: "address" }],
    name: "rejectKYC",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "role", type: "bytes32" },
      { internalType: "address", name: "callerConfirmation", type: "address" },
    ],
    name: "renounceRole",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "planId", type: "uint256" }],
    name: "resumePlan",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "role", type: "bytes32" },
      { internalType: "address", name: "account", type: "address" },
    ],
    name: "revokeRole",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "bool", name: "required", type: "bool" }],
    name: "setKYCRequired",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes4", name: "interfaceId", type: "bytes4" }],
    name: "supportsInterface",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "totalFeesCollected",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "unpause",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "newFeePercentage", type: "uint256" },
      { internalType: "address", name: "newFeeRecipient", type: "address" },
    ],
    name: "updateFeeConfig",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_primaryToken", type: "address" },
      { internalType: "address", name: "_usdtToken", type: "address" },
      { internalType: "address", name: "_usdcToken", type: "address" },
    ],
    name: "updateTokenAddresses",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "newImplementation", type: "address" },
      { internalType: "bytes", name: "data", type: "bytes" },
    ],
    name: "upgradeToAndCall",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [],
    name: "usdcToken",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "usdtToken",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "", type: "address" }],
    name: "userKYC",
    outputs: [
      { internalType: "address", name: "userAddress", type: "address" },
      { internalType: "enum KYCStatus", name: "status", type: "uint8" },
      { internalType: "uint64", name: "submittedAt", type: "uint64" },
      { internalType: "uint64", name: "reviewedAt", type: "uint64" },
      { internalType: "address", name: "reviewedBy", type: "address" },
      { internalType: "bytes32", name: "kycDataHash", type: "bytes32" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "", type: "address" }],
    name: "userPlanCount",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "", type: "address" }],
    name: "userPlanIdCounter",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "", type: "address" },
      { internalType: "uint256", name: "", type: "uint256" },
    ],
    name: "userPlanIdToGlobal",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "planId", type: "uint256" },
      { internalType: "uint256", name: "beneficiaryIndex", type: "uint256" },
      { internalType: "string", name: "name", type: "string" },
      { internalType: "string", name: "email", type: "string" },
      { internalType: "string", name: "relationship", type: "string" },
    ],
    name: "verifyBeneficiaryData",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "planId", type: "uint256" },
      { internalType: "string", name: "claimCode", type: "string" },
    ],
    name: "verifyClaimCode",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
] as const;

export default inheritXABI;
