import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import Providers from "./providers";
import NextTopLoader from "nextjs-toploader";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inheritxDisplay = localFont({
  src: "../public/fonts/BaseNeueTrial-CondensedBold.ttf",
  variable: "--font-inheritx-display",
  preload: true,
  display: "swap",
});

export const metadata: Metadata = {
  title: "InheritX",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inheritxDisplay.variable} antialiased`}
      >
        <NextTopLoader
          color="#33C5E0"
          height={3}
          showSpinner={false}
          easing="ease"
          speed={200}
          shadow="0 0 10px #33C5E0,0 0 5px #33C5E0"
        />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
